### ISSUE TITLE
Content local task

### ISSUE THREAD

**Issue by j4-m** [localgovdrupal/localgov_alert_banner#110]
Unless I'm missing something, it seems that accessing the Alter banners overview page (i.e. `admin/content/alert-banner`) requires you to know the path... it would be great if there was a local task so you could access it via tab when you're on the content admin pages. Given `admin/content/alert-banner` is a View this should just require a little extra configuration.

@andybroomfield can you confirm whether or not there is a different way access the page?

**Comment by andybroomfield** [comment]
@iam-jam Top menu ->Content -> Alert Banners

<img width="323" alt="Screenshot 2021-01-27 at 9 37 12 am" src="https://user-images.githubusercontent.com/1467480/105972213-4b957380-6083-11eb-87c7-a35bcc637986.png">

**Comment by iam-jam** [comment]
But it's missing from the local task tabs: 
![](https://puu.sh/HaXDo/b9732d4aa8.png)

**Comment by andybroomfield** [comment]
ok, might be worth adding that. I guess we are used to using the toolbar menu.

**Comment by iam-jam** [comment]
Yea I've just installed the module in a vanilla install so I'm missing admin_menu and consequently it's pretty hard to get to.

**Comment by tebb** [comment]
@mattrfletcher - I took a quick look, so this may be a bit off, but try:

- In your new test site
- Organise some kind of backup / snapshot.  backup_migrate or adminer (lando container)
- Export and stash the old config for view at admin/content/alert-banner (to use to test the update hook)
- Add a local tab to the view at: admin/content/alert-banner (d.o or Google will have examples)
- Export and stash the new view config
- Put/replace the relevant config in localgov_alert_banner's config/install directory
- Uninstall/reinstall the module -> check there's a local tab as reqd.
- Restore the backup.
- Update hook:  Probably need an update hook to ensure this is applied to existing sites. (d.o/Google)
- Run update.php and check the update is listed and applied.
- Let me know what I missed or better ways of doing this!!

- When it's working, ask someone if a test is needed.

**Comment by andybroomfield** [comment]
@tebb @mattrfletcher If your happy taking this on. The way to add Local tasks in Drupal 8 / 9 is to add it to the `localgov_alert_banner.links.task.yml` file in the root of the module and add the link to the alert banner admin view. 
I found some more infor here in case that is helpful. 
https://www.valuebound.com/resources/blog/drupal-8-how-to-create-the-local-tasks-through-custom-module

**Comment by tebb** [comment]
Oh well!  I tried :)  That's a lot easier!

So we don't need an update hook either?  Just clear (menu?) cache?

Thanks @andybroomfield
