### ISSUE TITLE
Schedule Alert banners

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#115]
Idea following on from conversation from Lambeth in product group, to schedule alert banners so user doesn't have to.
eg. Forms going down overnight.

Would require an optional enable and disable field, then use cron to set the banner live.

---------------------------
Update from https://miro.com/app/board/o9J_lHm9M2s=/?moveToWidget=3074457357810326495&cot=14

Also see https://github.com/localgovdrupal/localgov_alert_banner/pull/128 

**As a** content designer

**I want** to publish an alert banner temporarily across the top of selected pages on the site

**so that** I can inform users of a change to a service

**As a** content designer

**I want** to alert banners to unpublish automatically at a certain time

**so that** I don't have to remove them manually, and the website is free from out of date alert messages

--------------

Examples

    Bins not being collected this week
    Increase in parking charges - show the week before they come into force, and remove after a month

--------------

## Acceptance tests

At https://localgovdrupal.agile.coop/admin/content/alert-banner

1. Add an alert banner
    1. With content fields:
        1. Type of alert: Announcement
        2. Title (plain text)
        3. Message (formatted text with links)
    2. Add a path that the alert should display (Ben says: or type name of page to select it - allow multiple pages to be added)
    /council-tax
    3. Save
    4. See alert in the list
    5. Go to /council-tax (or to the pages selected above)
    6. Confirm that the message is not present
2. Update message to change publishing time
    1. Set to same day, 1 min ahead
    2. Save
    3. In the alert list, status is "Scheduled" (not sure what happens with "Set banner live" and "Remove banner" links - could show publishing day/ time instead?)
    4. Go to /council-tax after a minute
    5. Confirm message is displayed
3. Update message to change unpublishing time
    1. Set to same day, 2 mins ahead
    2. Save
    3. Go to /council-tax after 2 mins
    4. Confirm message is not present

--------------

## Related work

- Scheduling other content formats. Would be good to use same functionality and UX for consistency
- Scheduling whole sections. A bridge too far? Adnan also mentioned https://www.drupal.org/node/2968491

**Comment by andybroomfield** [comment]
Initial method would be to use the patch for scheduler and write an integration plugin
https://www.drupal.org/project/scheduler/issues/2096585

**Comment by finnlewis** [comment]
@andybroomfield noted on #138 

> Related Drupal.org issue.
> 
> https://www.drupal.org/project/scheduler/issues/2096585
> 
> I'd look to getting scheduling working on nodes first, once the project has decided which scheduling module to use as the default, the alert banner should implement it.
> 
> Some initial discovery was done in #128

**Comment by ekes** [comment]
The patch is for applying scheduler to entities other than nodes. In the larger picture there is the question if folk will also want to schedule other content, particularly if they have added workflow, this will require another module https://www.drupal.org/project/scheduler_content_moderation_integration.

The alternative for both is http://drupal.org/project/scheduled_transitions

This works out of the box with all entity types, and translations, but requires content workflow, so would require adding a content workflow (draft, live) and scheduling the transition between them for alerts.

**Comment by andybroomfield** [comment]
Would an acceptible alternative be to bake in scheduled live / removal into the module instead of relying on a dependency.

I'm a little worried on adding too much extra complexitiy to a module whose primary function is qucikly put a message accross the top of the site when there is a major disaster.

To support scheduled transitions we would be adding an extra workflow as @ekes mentions, I'm also not sure how that will work with the confirmation page.

**Comment by andybroomfield** [comment]
New comment on the issue from the maintainer of Scheduler.
https://www.drupal.org/project/scheduler/issues/2096585#comment-14106297
> @andybroomfield, I have taken your suggestion and added a new property schedulerEventClass to the plugin annotation, to allow you to specify your custom module's location. The default is \Drupal\scheduler\Event\Scheduler{Type}Events to match the existing. Here is the commit
> 
> The scheduler hooks now have slightly different names, to allow a proper general/specific naming convention, but for backwards compatibility the original node hooks are still executed. Hence I have removed the idListFunctionplugin property as this is unnecessary, but that should not affect you.
> 
> Please test and let me know it goes, because as far as I know there is nothing remaining to do, and it is ready for final testing before committing.

If the above gets merged into a release, I would suggest this tips the balance back in favour of using scheduler.

**Comment by andybroomfield** [comment]
From Slack
> @ channel just to share, the content workflow working group just made 2 decisions:
We are not going to use Workbench (https://www.drupal.org/project/workbench) for now as it adds complexity that we don't currently need, we will build on core views for content screens and extend as needed. 
We will use scheduled transitions (https://www.drupal.org/project/scheduled_transitions) , not scheduler (https://www.drupal.org/project/scheduler ) as it has the flexibility we need.

This means Alert banner will need to follow scheduled transitions, and add a workflow for the set live / remove banner option.
Question is if this means having a hard dependency on Workflow just to get schduling, or if its possible to use this module without it and detect if its installed to enable the schduling functionlity.

**Comment by stephen-cox** [comment]
@andybroomfield There was some discussion in Slack about this but moving them here for visibility.

We've chosen to use Scheduled Transitions for scheduling content in LocalGov and so it makes sense to use this for alert banners. This will mean adding workflow states to alert banners which involves code changes which won't be easy to extract out into a different module, adding a dependency on Drupal core's Content Moderation and Workflows module. Is there a problem with this?

Once alert banners use workflow states then using Scheduled Transitions with alert banners is trivial; it's just a little configuration.

**Comment by andybroomfield** [comment]
Just to confirm from standup.
We will be modifiing the alert banners module to include a dependancy on drupal core workflow, content moderartion and adding workflow config to the alert banner. This is because the confirmation page form needs to be edited to account for workflow being enabled.
We will then look to add scheduled transitions config in `config/optional` so it is only installed if scheduled transitions is enabled, and also add a way of detecting when schdeuled transitions module is enable to also then install alert banners scheduled transitions config.
/cc @stephen-cox
