### ISSUE TITLE
Save button missing when Gin admin theme is enabled

### ISSUE THREAD

**Issue by jhiron-wf** [localgovdrupal/localgov_alert_banner#116]
As stated in the issue title, when the Gin admin theme is enabled, the save button and the Published toggle do not render on an Alert Banner edit page, see screenshot below:

Top of Alert Banner edit page:
![Alert_Banner_Edit_Form_Top](https://user-images.githubusercontent.com/70009993/114390316-01a23100-9b8e-11eb-935b-3c02456e2139.png)

Bottom of Alert Banner edit page:
![Alert_Banner_Edit_Form_Bottom](https://user-images.githubusercontent.com/70009993/114390397-1da5d280-9b8e-11eb-9df0-2e1f3d5413d3.png)

Service Page edit page for comparison (the save button is contained within a sticky container):
![Service_Page_Edit_Form](https://user-images.githubusercontent.com/70009993/114390450-33b39300-9b8e-11eb-825d-2b6e90aabea1.png)

I also checked out editing a field on a paragraph type and although the save button did not appear in a sticky container, it was still present at the bottom of the page.

I am also logged in as /user/1 so I don't think it's a user permissions issue..

**Comment by andybroomfield** [comment]
Thanks for your bug report @jhiron-wf.
This is happening as Alert banner opts into node edit theming. However it looks like Gin is expecting something when it edits the form actions which the alert banner is missing.
Commenting out the following in `src/Form/AlertBannerEntityForm.php` does fix the issue, at the cost of loosing the sidebar options.
````php
$form['#theme'][] = 'node_edit_form';
````
So I think we need to decide if we want to keep the sidebar (and then fix alert banner form to provide whats needed for Gin to lift the actions up) or drop the sidebar options.

![screencapture-localgov-bhcc-test-admin-content-alert-banner-add-localgov-alert-banner-2021-04-12-16_08_54](https://user-images.githubusercontent.com/1467480/114417964-f8bf5880-9ba9-11eb-98d7-3460bee69901.png)

**Comment by willguv** [comment]
Thanks @andybroomfield. What are the sidebar options delivering in this case please? I could check but am supposed to be on leave today :)

**Comment by andybroomfield** [comment]
@willguv Its the Publishing and Authoring information, which gets sent to the bottom instead.
<img width="1437" alt="Screenshot 2021-04-12 at 4 45 10 pm" src="https://user-images.githubusercontent.com/1467480/114422953-a03e8a00-9bae-11eb-8f19-096cf3e0c897.png">

**Comment by willguv** [comment]
As long as the sidebar info is on the page, I think this fix is fine. Thanks for the info @andybroomfield
