### ISSUE TITLE
Specification for alert banner placement in different sections of the site

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#119]
We are looking ahead to sprint 12 and want to define the spec. 

https://trello.com/c/ML8TaTYD/288-targeting-alerts-to-a-specific-page

**Comment by willguv** [comment]
Thanks @finnlewis. I've asked Ben at Croydon (who raised this need most recently) to join the Trello board and add examples

**Comment by andybroomfield** [comment]
Closing this as #120 haa more of the conversation.
