### ISSUE TITLE
Template rationalisation: localgov_alert_banner

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#121]
This issue is to track the work needed to rationalise the templates and CSS to work with the new localgov_base theme. 

LocalGov Alert Banner is a useful case in point, as it has no dependencies on the rest of LocalGov Drupal distrubition.

Current issues / changes proposed: 

1.  classes need to change, assuming we are to follow Drupal best practce  https://www.drupal.org/node/1887918#formatting BEM https://en.bem.info/methodology/naming-convention/  

For example:  localgov_alert_banner--announcement would become localgov-alert-banner--announcement

This will lead to changes in CSS and tempaltes.

Fuerther to this, other changes to the template are probably needed to follow best practice.

## Question : how to do this without having a negative impact on users of localgov_theme

Suggestion:
 1. Copy templates and CSS / JS as it is over to localgov_skeleton theme.
 2. Ensure localgov_skeleton uses it's versions of JS / CSS / templates. 
 3. Start a new release branch for this work 
 4. Makes changes to templates / css / js within the module to bring it in line with standards. 
 5. Add any enhancements to the new localgov_base theme.

**Comment by ekes** [comment]
Alert Banner also provides its own entity so needs minimal default templating.

**Comment by andybroomfield** [comment]
I think it was also agreed early on that alert banner will always provide some CSS so it can be used out the box, however  should adopt the new styling conventions for the banner colours using css variables.

**Comment by andybroomfield** [comment]
Closing as done
