### ISSUE TITLE
Tag 1.0.0

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_alert_banner#124]
As per localgovdrupal/localgov#194 localgovdrupal/localgov#200

PR: template changes to be discussed not blocking
Issues: nothing blocking, mainly new features.

**Comment by ekes** [comment]
@andybroomfield Do you want to tag this one? Is there anything I missed that wants doing before that?

**Comment by andybroomfield** [comment]
@ekes I'll take it, I want to review some of the issues first but should be no problem to go ahead and tag.

**Comment by ekes** [comment]
https://github.com/localgovdrupal/localgov_alert_banner/releases/tag/1.0.0
