### ISSUE TITLE
Publish alert banners on selected sections of the site

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#137]
From: https://miro.com/app/board/o9J_lHm9M2s=/?moveToWidget=3074457357810326499&cot=14

Also see: https://github.com/localgovdrupal/localgov_alert_banner/pull/129
And https://www.drupal.org/project/condition_field 

**As a** content designer

**I want to** publish an alert banner across the top of selected pages on the site

**so that** I can notify citizens of a change to a specific service without displaying the alert on every page

--------------

Examples

- Bins not being collected from specific streets
- Increase in parking charges
- Call centre not working

--------------

## Acceptance tests

At https://localgovdrupal.agile.coop/admin/content/alert-banner

1. Add an alert banner
    1. With content fields: 
        1. Type of alert: Announcement
        2. Title (plain text)
        3. Message (formatted text with links) (review format - content designer asked for messages with headings, bold text, links. Is title optional rather than mandatory?)
    2. Add a path (/council-tax)that the alert should display (Ben says: or type name of page to select it - allow multiple pages to be added)
    3. Save 
    4. See alert in the list (does the list show list of pages targeted? some content designers mentioned confirmation)
    5. Go to /council-tax (or to the pages selected above)
    6. Confirm that the message is not present

2. On the alert list, click "set banner live"
    1. Go to /council-tax
    2. Confirm that the message is displayed
3. Update message to change copy
    1. Log out (do we need this step?)
    2. Confirm that message copy is updated across all pages
4. On the alert list, click "remove banner"
    1. Go to /council-tax
    2. Confirm that the message is not displayed

**Comment by finnlewis** [comment]
@stephen-cox you're doing some work on this... shall we assign it to you ?

**Comment by stephen-cox** [comment]
Current code for this is in the [feature/137-conditional-placement](https://github.com/localgovdrupal/localgov_alert_banner/tree/feature/137-conditional-placement) branch.

It adds a new visibility field, building on the work that @andybroomfield did.

It currently only adds the field to the existing alert banner type and works for new installs. Do we want this change applied to other alert banner types and existing installs?

**Comment by willguv** [comment]
@stephen-cox can you get me a screenshot as it's hard to picture

**Comment by stephen-cox** [comment]
Here's a screenshot of the alert banner edit form with the added visibility field

![Screenshot - Add alert banner](https://user-images.githubusercontent.com/7189914/119322403-82684880-bc75-11eb-89c5-80e7ede1132b.png)

**Comment by finnlewis** [comment]
@willguv suggests removing the 'role' and 'content type' options.

**Comment by finnlewis** [comment]
@andybroomfield suggests inserting the field into the entity directly.

**Comment by andybroomfield** [comment]
@finnlewis @stephen-cox However it would be good to be able to still use the plugin architecture so we hve our own requirments for a consition plugin that will pick a service and display in them, and I suspect others wil have similar / own requirements they would like to extend upon.

**Comment by andybroomfield** [comment]
See also #108 which is another solution (leave it as a config field, but always create it when making a new banner).

**Comment by stephen-cox** [comment]
@andybroomfield Taking inspiration from issue #108, I have created a `postSave` method that copies the configuration for the visibility field to new alert banner types; see https://github.com/localgovdrupal/localgov_alert_banner/pull/142/commits/ccb9f59f789033eea034e3b607902a8ae160dca3. It would be easy to extend for other fields and so would solve that issue too.

Do we want to add this field to existing LocalGov installs? If so we'll need an update hook that does something similar.
