### ISSUE TITLE
Schedule alert banners to publish/ unpublish at selected times

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#138]
Also see https://github.com/localgovdrupal/localgov_alert_banner/pull/128 

**As a** content designer

**I want** to publish an alert banner temporarily across the top of selected pages on the site

**so that** I can inform users of a change to a service

**As a** content designer

**I want** to alert banners to unpublish automatically at a certain time

**so that** I don't have to remove them manually, and the website is free from out of date alert messages

--------------

Examples

    Bins not being collected this week
    Increase in parking charges - show the week before they come into force, and remove after a month

--------------

Acceptance tests

At https://localgovdrupal.agile.coop/admin/content/alert-banner

1. Add an alert banner
    1. With content fields:
    Type of alert: Announcement
    Title (plain text)
    Message (formatted text with links)
    Add a path that the alert should display (Ben says: or type name of page to select it - allow multiple pages to be added)
    /council-tax
    Save
    See alert in the list
    Go to /council-tax (or to the pages selected above)
    Confirm that the message is not present
    Update message to change publishing time
    Set to same day, 1 min ahead
    Save
    In the alert list, status is "Scheduled" (not sure what happens with "Set banner live" and "Remove banner" links - could show publishing day/ time instead?)
    Go to /council-tax after a minute
    Confirm message is displayed
    Update message to change unpublishing time
    Set to same day, 2 mins ahead
    Save
    Go to /council-tax after 2 mins
    Confirm message is not present

--------------

Related work

    Scheduling other content formats. Would be good to use same functionality and UX for consistency

    Scheduling whole sections. A bridge too far? Adnan also mentioned https://www.drupal.org/node/2968491

**Comment by andybroomfield** [comment]
Related Drupal.org issue.

https://www.drupal.org/project/scheduler/issues/2096585

I'd look to getting scheduling working on nodes first, once the project has decided which scheduling module to use as the default, the alert banner should implement it.

Some initial discovery was done in #128

**Comment by andybroomfield** [comment]
Also this duplicates #115 so best to keep the discussion in one place.

**Comment by finnlewis** [comment]
Woops! Closing in favour of #115 , thanks @andybroomfield
