### ISSUE TITLE
Replace content.short_description in template with content|without('title', 'link')

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#143]
I think it was this way before, but its since been changed (@markconroy ?)
This means the alert banner cannot have extra fields without a custom template.
Before I think we used `content|without('title', 'link')` so that any extra field gets printed.

I noticed this when experimenting with Layout Builder on the banner which wraps the fields in the content variable with the region and nothing was being printed out. The fix in the description fixes it.

**Comment by markconroy** [comment]
I don't remember it being `{{ content|without... }}` before.

But I certainly think it should be.

We have an `if` statement. Should we remove that clause? If we leave it in and someone fills out another (new) field, but not the summary field, then that new field will not print.

**Comment by andybroomfield** [comment]
Could we action this. I can raise a PR.
I don't think we need to wrap with an if statement as worst case its an empty div that gets rendered.
