### ISSUE TITLE
Display (and edit) more than one banner

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#15]
In the original spec at BHCC more than one banner was anticipated, though this was changed to 1 before deployment. There is also an admin view that can show multiple banners in case users want to keep multiple banners ready for publishing. The support is still present, though it was shortcutted to only allow edit the first banner.

We need to decide if:-

1. We stick with current implentation (1 banner, that can be edited or removed). If thats the case it would be better to revert back to an initial implementation which stores the banners in state rather than as a content entitiy
2. We display 1 banner, but allow multiple banners to be avalible to edit. We need to remove the menu shortcut that links directly to edit the first banner, and link it to the admin view. Sites that wanted to keep the BHCC behaviour can use a custom module to reimplement the shortcut
3. We display more than one banner. We will need to decide on some ordering for the banners (death -> major -> minor). This will also require altering the custom check in the event subscriber that prevents more than one banner being published at once.

**Comment by andybroomfield** [comment]
Ideal would be this was administrator editable, however we need a sensible default for now.

**Comment by andybroomfield** [comment]
Example with more than one banner (using the hidden admin at /admin/content/alert-banners)

![Screen Recording 2020-06-16 at 10 54 44 am](https://user-images.githubusercontent.com/1467480/84760820-7c2b1000-afc0-11ea-9e3e-48ed6121bd36.gif)

**Comment by danchamp** [comment]
I like option 2. It allows the quick and easy re-use of some standard alerts like holiday hours / office closures, with minimal editor / administrator effort, and increased consistency.

**Comment by Adnan-cds** [comment]
Drawing attention of @willguv

**Comment by Adnan-cds** [comment]
Hi Andy,
For this sort of use cases, I find [EntityQueue](https://www.drupal.org/project/entityqueue) quite useful.  Individual site's can override the number allowable items in the queue which should resolve some of the dilemma IMHO.

FAO @andybroomfield

**Comment by andybroomfield** [comment]
Thanks @danchamp for your comment.

@Adnan-cds I have thought about entity que, though for the time being it would be better to try and reduce depandancies. The other issue is its a requirement that a content editor can add the banner quuckly in an emergency so needs to be little friction and entity queue has been found to be a little combersume at BHCC. (But maybe something to use behind the scenes in future).

**Comment by willguv** [comment]
@andybroomfield @danchamp From a product point of view, I like option 2 provided it's not lots of extra dev work. If it's a big job, we should chat about it.

We've not had the need to create standard alert banners, but I can see this being very useful.

@Adnan-cds does the big bang announcement work this way already? It would be good if we could standardise how alerts are edited and published.

**Comment by Adnan-cds** [comment]
> does the new Croydon big bang announcement work this way already?

Hi Will, yes, we use paragraphs (AKA Page components) to create Big bang announcements and then add them to an entity queue (AKA the page queue).  These Paragraphs persist even after they are removed from the queue.  This makes it possible to use them later.  For better UX, we have added a menu item for editors at "Manage > Content > Page queue > Big bang announcement".  The Service status thing also works in a similar way although in this case we use the existing Service status content type instead of Paragraphs.

@willguv @andybroomfield

**Comment by andybroomfield** [comment]
Thanks @Adnan-cds @willguv 
It looks like option 2 is how it will go forward, the functionality is already present but hidden as it was a last minute change in dev work at BHCC. I'll leave the issue open if other councils / devs wish to comment, though work on the assumption that option 2 is what we are going with.

Oiut of interest, does the big band announcement work accross the site or is it home page / specific pages only?

**Comment by Adnan-cds** [comment]
> does the big band announcement work accross the site or is it home page / specific pages only?

It is for the homepage only.  As per the requirement, I have told the Views block (which sources the announcements from the EntityQueue) to only appear in the homepage.  An unstyled version is pending testing at https://lbc-app-w-corpwebsite-dev2.azurewebsites.net/

@andybroomfield

**Comment by andybroomfield** [comment]
@Adnan-cds Presumably a block though so could go anywhere?

**Comment by Adnan-cds** [comment]
> Presumably a block though so could go anywhere?

Good morning :)  That's right Andy.

The main difference between Big bang announcement and Site alert is that Big bang announcements cannot be closed!  It also has some extra styling requirements.

FAO @andybroomfield

**Comment by andybroomfield** [comment]
Thanks, I think for now we will push ahead and convert this from an ECK to custom entity with the option for more than one banner. We can look in the future if there is any chance to merge this with big bang announcements.

**Comment by willguv** [comment]
@andybroomfield this seems like a good plan - thanks

It would be good to see if a general alert function could provide both the alerts we have now, and more prominent alerts like BB ones

**Comment by andybroomfield** [comment]
Archiving discussion.
