### ISSUE TITLE
Do we need the "session" cache context?

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_alert_banner#150]
Hi Andy,
Our **cache_render** MySQL table is getting flooded with alert banner blocks.  It appears that each and every anonymous page request (that's not already in cache_page) is adding an alert banner block entry in cache_render.  This is because all anonymous page requests have different sessions and the alert banner is using the ["session" cache context](https://github.com/localgovdrupal/localgov_alert_banner/blob/ef0149e9b22b2dd92520a63876916a400a29b069/localgov_alert_banner.module#L38).  Do we really need the *session* cache context on Alert banner entities?

Please note that while there are only a few thousand pages in our site, the presence of the directory facets have created an unlimited combination of page URLs and page requests for those URLs.  That's what's causing the flooding :(

The **url.path:is_front** cache context is also contributing to the flooding due to a typo.  I have already raised a [pull request](https://github.com/localgovdrupal/localgov_alert_banner/pull/149) for that.

@andybroomfield

**Comment by andybroomfield** [comment]
Ouch, that's got to be harsh. Let's take a look at that.
Do you use the anonymous internal page cache?

I think there is some ongoing discussion on the correct cache tags to use. The urls where added due to the presence of condition field.

Not sure about session cache, we do need to check the cookie but again that's in JavaScript for now. Maybe something to do with condition field as that has a user role plugin.

@stephen-cox able to help debug?

**Comment by Adnan-cds** [comment]
> Do you use the anonymous internal page cache?

That's right.

> Maybe something to do with condition field as that has a user role plugin.

If that's the case then perhaps we can cover that with the *user.role* cache context?  Whatever we do, we will need some tests.

Thanks for the prompt response :)

**Comment by andybroomfield** [comment]
I think we might just be able to remove the cache contexts from localgov_alert_banner.module `localgov_alert_banner_entity_build_defaults_alter`
````php
$build['#cache']['contexts'][] = 'cookies:hide-alert-banner-token';
$build['#cache']['contexts'][] = 'user.roles:anonymous';
$build['#cache']['contexts'][] = 'session';
````

Should the cache tags be generated here, or should they now move to the entity? This is a holdover from when this was built using ECK.

**Comment by Adnan-cds** [comment]
> Should the cache tags be generated here, or should they now move to the entity? 

Entity may be better.  Example from [core's path_alias module](https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/path_alias/src/Entity/PathAlias.php#L168).

**Comment by stephen-cox** [comment]
Certainly better to remove the `localgov_alert_banner_entity_build_defaults_alter` hook and move the cache contexts and tags to the entity. I made a start at it here: https://github.com/localgovdrupal/localgov_alert_banner/blob/8f0621c7f933344319c133df0f6d2104eb7893b9/src/Entity/AlertBannerEntity.php#L393

I suspect we don't need the session context here. Is the hide alert banner functionality entirely controlled with JS and cookies? If so then there's no need to vary the cache on a PHP session cookie.

I don't think there's anything to vary this on user role either. There's the possibility that the visibility field sets this but this is covered already. So we can likely drop that user role context as well.

Is there any reason why the front page is treated differently than other pages when displaying alert banners? If not then this context can be dropped.

My suggestion would be to move the cache context and tags into the entity as mentioned. One thing to check will be that the correct cache contexts and tags are loaded by the alert banner block: https://github.com/localgovdrupal/localgov_alert_banner/blob/ef0149e9b22b2dd92520a63876916a400a29b069/src/Plugin/Block/AlertBannerBlock.php#L189

**Comment by andybroomfield** [comment]
> Is there any reason why the front page is treated differently than other pages when displaying alert banners? If not then this context can be dropped.

There is a slightly different template for the front page, as the the font is sometimes bigger.
