### ISSUE TITLE
Assign view alert permission to anon users when creating new alert banners.

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#151]
Or we need to set the default view all alert banners permision?
So on initial install, I noticed that anon users can't actully view any banner contents unless this permission is set.

**Comment by andybroomfield** [comment]
Does our entity even check for permission to view?
I had a strange effect on an old install I had the scheduler work on where the banner wasn't visible.
But everywhere else its possible to see it without permission.
I think by default we should let anon users see the banner, and may not even need seperate permissions to view.

**Comment by andybroomfield** [comment]
In `AlertBannerEntityAccessControlHandler` Should we return `return AccessResult::neutral();`
https://github.com/localgovdrupal/localgov_alert_banner/blob/ef0149e9b22b2dd92520a63876916a400a29b069/src/AlertBannerEntityAccessControlHandler.php#L51
@stephen-cox @Adnan-cds ?
... And is the above code even being called?

**Comment by andybroomfield** [comment]
Ok, so the above gets called, but only when viewing the entity directly at /admin/content/alert-banner/4
That makes sense as we want to disallow access to that url (and eliminate it in the future?)

We don't currently check for access to the alert banner entity when rendering the block. This makes sense as in most scenarios you will want anonymous users to be able to see the banner. However there are possible scenarios where an internal only banner type would be used only displayed to authenticated users. This could be done as a seperate block or using the user condition plugin, but it makes more sense to be able to restrict the entity.

Also not checking access in Drupal 9 is throwing a deprecartion warning for drupal 10, that accessCheck(TRUE) (or false) will be required.

The previous ECK based version used a Route Subscriber to lock out the page. That was removed in #135 as it was never actully used in the Localgov version. Maybe it is time to bring that back and have a seperate view entity page permission?

**Comment by stephen-cox** [comment]
Reading the code, without running it, it would appear we want to give the `view all localgov alert banner entities` permission to anonymous users, which should allow anonymous users to view all banners.

Using the visibility field with the roles condition plugin enabled should allow the targetting of alert banners by users role and the alert banner block _should_ handle this possibility as it calls the `isVisible` method on each alert banner when checking whether it should be displayed https://github.com/localgovdrupal/localgov_alert_banner/blob/ef0149e9b22b2dd92520a63876916a400a29b069/src/Entity/AlertBannerEntity.php#L250

The block doesn't explicitly check permissions, so maybe we need to add this; maybe as a check to the `isVisible` method.

**Comment by finnlewis** [comment]
@andybroomfield hoping to pick this up in the next few weeks.

**Comment by finnlewis** [comment]
@andybroomfield still hoping to get this done by the end of sprint 10. Do flag if you want someone else to take this over @andybroomfield
