### ISSUE TITLE
Alert banners appear below Subsite banners

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_alert_banner#153]
Subsite banners have a weight in config of -7, meaning they appear above alert banners in the Banner region:

https://github.com/localgovdrupal/localgov_subsites/blob/2.x/config/optional/block.block.subsitebanner.yml

<img width="1264" alt="Screenshot 2021-07-01 at 18 24 25" src="https://user-images.githubusercontent.com/261421/124165367-96d00a00-da99-11eb-84ca-4b2d1af74ed9.png">

Propose setting Alert Banners default weight to -100 or similar.

**Comment by andybroomfield** [comment]
Is this still a present issue?
We could set the default weight of the block, but we will also need to update the config which might be a problem for those who have moved the blocks.
