### ISSUE TITLE
Replace ECK with custom entity

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#16]
As nice as ECK is we really should ship with our own entity.
We can use Drupal console to scaffold.

We need to decide if :-

1. Use a custom content entity, so as now but just not ECK.
2. We want to just go back to using state (1 banner support only)
3. Use a custom node content type, so it appears under create content.

**Comment by andybroomfield** [comment]
I would favour 1 as it fits with the idea of content being stored in entities, however its not a page so it doesn't really belong on a node entity.

**Comment by ekes** [comment]
Functionality is like a block, but constrained to a specific use case right?
It's even simpler than for example Status updates?

There's no access control, no page view, path? It's not such that it should feel like adding content into the site for an administrator? It might even be that it should be an 'unusual' or 'different' task?

It tend toward 1 in that case; 
although using a node content type, as status does is also an option.

**Comment by ekes** [comment]
Addition: I agree it would be good to get rid of the unnecessary dependencies (eck, flag).

**Comment by andybroomfield** [comment]
@ekes yes no page view, although the ECK path is currently purposed for preview purposes.
Otherwise its essentially a quick custom block for displaying persisntatly accross the top of the page. Its currently reachable on install under content -> alert banner.

**Comment by andybroomfield** [comment]
Also should rename the entity from alert_banner to `localgov_alert_banner`

**Comment by andybroomfield** [comment]
See also #18. Fields need to be renamed.

**Comment by andybroomfield** [comment]
There is also the admin view to update at http://localgov.lndo.site:8000/admin/content/alert-banners and the display view http://localgov.lndo.site:8000/admin/structure/views/view/alert_banner
The flag `put_live` will need to updated to the new entity.
The template will also need to update `eck-entity--alert-banner.html.twig`

**Comment by andybroomfield** [comment]
For nameing conventions see https://github.com/localgovdrupal/localgov/wiki/Naming-conventions

**Comment by danchamp** [comment]
That all makes sense. Presumbly also move remove_hide_link to the entity to remove the flag dependency?

**Comment by andybroomfield** [comment]
@danchamp Yes, think the hide link can go. I'd like to keep put live as a flag for now to keep the modal confirm behaviour until we tackle #17.

**Comment by andybroomfield** [comment]
Fixed with #26. Other issues added as followup.
