### ISSUE TITLE
Default the unplublish other alert banners to off 

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#160]
... This is now the default behaviour at BHCC (done with a hook form alter).
I think it should actully be default behaviour now as this dates from a time when converting from only 1 banner to allowing multiple where multiple was a rare use case. With conditional banners now added this can be extra confusing.

I'd actully go one step further and remove this feature now, as we can't assume all banners should really be unpublished.

**Comment by danchamp** [comment]
+1 to removing it as a default.

Not completely convinced removing it completely is ideal - it lists the banners that will be unpublished which provides something of a safety net.

Could it be a permission-based feature and leave site owners to decide if they want to enable/disable it?

Or if it is removed, add the ability to select and unpublish a batch from the Manage Alert Banners admin page?

**Comment by andybroomfield** [comment]
I'll add a PR to swap the default to off on this.
This also has implications for scheduled transitions #159 (which won't get to this page by default)
So it might be time to remove it entirly?

**Comment by andybroomfield** [comment]
This will be a good first issue if someone is looking to work on something.
