### ISSUE TITLE
Replace flag dependency?

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#17]
This module also relies on flag for two options, to put the banner live (publish) and to remove the hide link (it was a request from public health that Covid info on BHCC could not be hidden).

These could be replaced with simple status booleans to avoid the dependancy on flag
Flag also allows the module to use event subcriber to trigger options when put live. Right now this is to unflag any other banners once it is put live, it could also be used to trigger an email alert once a banner is put live.

**Comment by andybroomfield** [comment]
One feature that flag does provide is the modal to confirm to switch on the banner, which is a feature that would be good to keep.

**Comment by ekes** [comment]
The flag event also unpublishes any other alert - so there is only ever one. All this can be hung on the status, on the save. The token is also generated, but this is also done on the save by hooking in. Both can be handled in the custom entity itself.

Regarding UX. I feels like the status doesn't want to be on the edit form, at the moment in manual testing at least, I don't get the confirmation with the flag on the form. But I get the sense that a two step operation. Create, and publish separately makes sense for this operation.

So working idea:-
 * create/edit form redirects to the list of alerts
 * list of alerts shows which -if any- is currently active and each alert has link to set it (in)active
 * on clicking set alert active there is an intervening confirmation form 'Are you sure ...'

**Comment by andybroomfield** [comment]
@ekes You'll get the pop up in #49.

**Comment by andybroomfield** [comment]
User stories are this comment
https://github.com/localgovdrupal/localgov/issues/67#issuecomment-642956764

**Comment by ekes** [comment]
> @ekes You'll get the pop up in #49.

Yer but I can (could as I've removed it ;) put the alert live with a checkbox on the form with the flag - and it doesn't do the pop-up that way - just from the flag link in the view. The user stories don't cover the banners list? 

For the story it would sound more like on the submit form, you'd want to go to a preview version (like comments do), and then confirm publish then?

**Comment by andybroomfield** [comment]
@ekes Yes I think flag is only configured to do that on the view. 
I think we will still need to publish checkbox, its just it should offer a caution warning if possible. Maybe not for now as your on the banner your editing.

The admin view came later in the development process, and then get canned at BHCC for just edit one banner. However it needs the caution as you can put the banner live on that page without going into the edit page.

This is what was demoed to product group on Slack. (and discussion in #15).
![Screen Recording 2020-06-16 at 10 54 44 am](https://user-images.githubusercontent.com/1467480/84760820-7c2b1000-afc0-11ea-9e3e-48ed6121bd36.gif)

**Comment by ekes** [comment]
Follow-up on #56 closing this one as the actual flag dependency is now removed.
