### ISSUE TITLE
Can't see Moderation control form element

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_alert_banner#174]
I am trying to add/edit an Alert banner in a fresh LocalGov site with ```localgovdrupal/localgov_alert_banner:"1.2.0 as 1.1.1"``` and I can't see the Moderation control element in the add/edit form.  Is this normal?

Please note that the form display for alert banners include the Moderation control element.  Screenshot from the edit form attached:
![screenshot-alert-banner-edit-form-no-moderation-control](https://user-images.githubusercontent.com/50206849/134203197-457cad4d-0005-4fa2-9588-e8b7dd018c50.png)

**Comment by andybroomfield** [comment]
Yes, Alert banners should not show the moderation form as the confirm form is what puts the banners live.
(This is how we are able to work with scheduled transitions).

**Comment by andybroomfield** [comment]
We should work out what happens if the moderation form is placed, as if it is, we should then skip the confirmation form.

**Comment by andybroomfield** [comment]
If its placed, you can't actually set the banner live on the confirmation screen.
