### ISSUE TITLE
Rename fields to use the localgov format

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#18]
Follow the example in localgov_services and rename `field_` to `localgov_alert_`...
(Check format before adding).

**Comment by andybroomfield** [comment]
The entity in #26 uses them unprefixed, however they form part of the entity so I'm not sure thats required. Let us know best practice @ekes @stephen-cox.

**Comment by stephen-cox** [comment]
@andybroomfield @danchamp There's a wiki page on naming conventions: https://github.com/localgovdrupal/localgov/wiki/Naming-conventions
We're only renaming fields where necessary, but when we do we prefix them with `localgov_`
