### ISSUE TITLE
[Bug] Add moderation control for Full page banner

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_alert_banner#188]
Without moderation control, we cannot publish/unpublish Full page alert banners :(

**Comment by andybroomfield** [comment]
When I enabled the full page alert module, the banner type that is creates was added to the alert banner workflow.
It may be that you had full page alerts before the scheduled tasks update was added?

Steps I used to try and reproduce.
- Install localgov alert banner
- Verify alert banner workflow exists
- Enable the full page alert banner module
- Create and set live a full page alert banner
- On the confirm page, was able to confirm to set live.
- I also verified that the workflow was added to the full page alert banner type.

**Comment by Adnan-cds** [comment]
Hi Andy,
Yes, you are right.

I will try to fix the relevant update hook implementation so that existing sites are taken care of.

**Comment by andybroomfield** [comment]
Did you fix this @Adnan-cds ?

**Comment by Adnan-cds** [comment]
Hi Andy,
I will check this and get back to you.

**Comment by Adnan-cds** [comment]
I can't reproduce the problem on a fresh LocalGov install.  This can be closed :)

**Comment by andybroomfield** [comment]
Thanks for looking @Adnan-cds
