### ISSUE TITLE
Add basic CSS / colours

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#19]
We will need to have some basic css for the banners, though themes will override.
Should we add colours here?

**Comment by andybroomfield** [comment]
Blocked by #27

**Comment by andybroomfield** [comment]
We should liases with theme @danchamp @cjstevens78 @ekes @stephen-cox and decide if we do this in the module or in the theme.

**Comment by stephen-cox** [comment]
@danchamp @andybroomfield Just to confirm what we discussed at review; I've been adding structural CSS to modules and a maybe a little extra colours and such like. The idea being that if the module is installed on it's own it will work, even if more styling will be need to make it look good.

**Comment by danchamp** [comment]
Closed by #69
