### ISSUE TITLE
Update automated tests to only run coding standards and phpunit tests on this repository

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#191]
See https://github.com/localgovdrupal/localgov/issues/423

Just creating an issue here to give this a go on the localgov_alert_banner

Ideally, I think we should be able to 

- [x] test against multiple versions of PHP (7.4 and 8.1)
- [x] only run phpcs checks on code in this repository
- [x] only run phpstan checks on code in this repository
- [x] only run PHPUnit tests provided by this repository

Perhaps we can then set full integration tests to run on the install profile or perhaps on a pull request to the release branch?

**Comment by finnlewis** [comment]
@andybroomfield any thoughts these suggestions?

**Comment by finnlewis** [comment]
I think I've got the first three working!

**Comment by andybroomfield** [comment]
Yes, these sound good as tests. I think for the last, will we need a custom test script that only runs `phpunit web/modules/contrib/localgov_alert_banner`

**Comment by finnlewis** [comment]
@andybroomfield I think I got that to work with:

https://github.com/localgovdrupal/localgov_alert_banner/pull/192/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L189-R186

Tests ran in 5m 17s

**Comment by finnlewis** [comment]
Note from merge Monday: 
 - there are skipped tests on the Merge 
 - deprecated code is returning lots of issues.

- [ ] confirm if the deprecated code tests are behaving or what are the notices?
- [ ] confirm why the skipped test is skipped
- [ ] Andy suggested considering running phpunit with --testdox (although does not work with paratest)

See https://github.com/localgovdrupal/localgov_alert_banner/runs/5872911531?check_suite_focus=true

**Comment by andybroomfield** [comment]
I think we did this?

**Comment by andybroomfield** [comment]
I'm closing this on on the grounds that I think this is done. Please reopen if still required.
