### ISSUE TITLE
The drupal/condition_field patches failed to apply

### ISSUE THREAD

**Issue by tran-bigbluedoor** [localgovdrupal/localgov_alert_banner#214]
Currently, the drupal/condition_field patches are blocking update/install with composer:
<img width="1215" alt="Screenshot 2022-06-01 at 15 10 19" src="https://user-images.githubusercontent.com/102959744/171440651-5f24d882-9bea-46f8-b358-466cd7e0dbb6.png">

Suggestion: Remove the patches from composer.json because the new version of drupal/condition_field module has already applied these changes from the patches.

**Comment by andybroomfield** [comment]
Ha! New release day :-) 
(Also has official Drupal 10 support which should fix #207.

**Comment by stephen-cox** [comment]
@tran-bigbluedoor @louwrense This issue should now be fixed with the [Alert Banner 1.4.1](https://github.com/localgovdrupal/localgov_alert_banner/releases/tag/1.4.1) and [Services 2.0.10](https://github.com/localgovdrupal/localgov_services/releases/tag/2.0.10) releases.
