### ISSUE TITLE
Cookie Warning if SameSite Not Set

### ISSUE THREAD

**Issue by rgcarr** [localgovdrupal/localgov_alert_banner#239]
When the cookie is set for an alert banner (when the 'Hide' button is clicked) Firefox generates a warning message in the console:

    Cookie “hide-alert-banner-token” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Although it should be harmless, I'm finding that the Cookie isn't always being set in Firefox.

Could this SameSite setting be added to localgov_alert_banner/js/alert_banner.js:

`cookies.set('hide-alert-banner-token', new_cookie, { path: '/', expires: 30, SameSite: 'Lax' });`

I couldn't see any downsides.

[alert_banner_samesite_warning.patch](https://github.com/localgovdrupal/localgov_alert_banner/files/10882119/alert_banner_samesite_warning.patch)

**Comment by andybroomfield** [comment]
Thanks for raising @rgcarr. Are you able to open a Pull request with your patch and we can test?

Thanks.

**Comment by rgcarr** [comment]
@andybroomfield I've got to be honest, spent an hour looking at docs on how to create a pull request on Github, and I'm getting nowhere. Not done this before. I'm kinda lost at the 'Creating a fork' stage. Terrified when the Web IDE opened and I appeared to be editing the source code directly.

Will have to come back to this next week when I have some more spare time.

**Comment by rgcarr** [comment]
I think I created a PR. That was my best effort. Let me know if that's what's needed

**Comment by andybroomfield** [comment]
Thanks @rgcarr i will take a look at this for you.

**Comment by rgcarr** [comment]
Thank you @andybroomfield. Trivial stuff really, but thanks for your time and support

**Comment by andybroomfield** [comment]
Fixed in #240 and released as part of 1.5.5.

**Comment by rgcarr** [comment]
Seems there was a related Drupal issue too https://www.drupal.org/node/3150614
