### ISSUE TITLE
Alert banner with empty Link text should show "More information", but nothing shows 

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_alert_banner#245]
On a clean install with localgov_base, there's this wording when creating an Alert banner ("If you don't write anything here, we will use: More information").

![image](https://github.com/localgovdrupal/localgov_alert_banner/assets/19519457/dd8e38e4-c41b-4a9f-be71-28cd8974b15e)

But looking at the banner on the site, I see no link at all:

![image](https://github.com/localgovdrupal/localgov_alert_banner/assets/19519457/ac055e44-6ff3-4933-93cc-e83f1c5daaf1)

**Comment by andybroomfield** [comment]
With the default theme set to oliveo, the More information link is displayed.
Maybe this is an issue with Localgov base?

<img width="860" alt="Screenshot 2023-05-12 at 10 37 48 am" src="https://github.com/localgovdrupal/localgov_alert_banner/assets/1467480/30c22993-3bee-4235-b6a0-0461259b702f">

**Comment by andybroomfield** [comment]
And a test on BHCC theme
<img width="1187" alt="Screenshot 2023-05-12 at 10 39 46 am" src="https://github.com/localgovdrupal/localgov_alert_banner/assets/1467480/f4ea4c8e-f4bf-41d5-bfe8-bd9ef8ee60fe">

**Comment by andybroomfield** [comment]
This is set by [localgov_alert_banner.page.inc](https://github.com/localgovdrupal/localgov_alert_banner/blob/183c2d988de59b2d1c69a1d51644ac8d61a4246b/localgov_alert_banner.page.inc#L36)
````php
// Set default link text if field exists.
  if ($entity->hasField('link')) {
    if ($entity->get('link')->title === '') {
      $variables['content']['link'] = Link::fromTextAndUrl(t('More information'), Url::fromUri($entity->get('link')->uri))->toString();
    }
  }
````
Is localgov_base overriding this @markconroy ?

**Comment by ctorgalson** [comment]
@andybroomfield sort of. It's that the existing assignment to `$variables['content']['link']` quoted above _changes_ the render array to from a LinkItem to a GeneratedLink, I believe.

@petrillek just noticed this too. I'll create a PR in a few minutes.

**Comment by andybroomfield** [comment]
Closing as this looks fixed.
