### ISSUE TITLE
JS Cookie library deprecated in Drupal 10.1, removed in Drupal 11 without replacement

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#271]
> The core/js-cookie asset library is deprecated in Drupal 10.1.0 and will be removed in Drupal 11.0.0. There is no replacement. See https://www.drupal.org/node/3322720

So does [this](https://www.drupal.org/node/3322720) mean we need to declare a dependancy on it directly and ask users to download it to the libraries folder? Or just include a copy.

**Comment by keelanfh** [comment]
... or refactor the code to remove the dependency, could be done at the same time as removing the jQuery dependency (#201)

**Comment by millnut** [comment]
I would probably recommend using vanilla javascript and then switching out cookies in favour of localstorage.

**Comment by siliconmeadow** [comment]
On the 4 Apr 2024, they updated that change record with a solution to switch to a contrib module which is unsurprisingly called [JS Cookie](https://www.drupal.org/project/js_cookie). It's maintained by [Dave Reid](https://www.drupal.org/u/dave-reid) who is prolific.

**Comment by markconroy** [comment]
That js-cookie module just does one thing: get the js-cookie JS from https://github.com/js-cookie/js-cookie so that it can be used in a Drupal site.

I think the simplest thing is to update our `.libraries.yml` file to fetch that JS file for us and then we don't need to worry about needing the Drupal module.

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by andybroomfield** [comment]
Tthe current plan given we don't use many of the features, just set and read back a cookie, is to try and remove the dependency. @millnut is trying to switch to local storage in #322.
I really would like to avoid having sites load a Javascript file from a CDN.

**Comment by markconroy** [comment]
What's the thinking behind using localStorage instead of a cookie?

**Comment by andybroomfield** [comment]
We've removed it from the main module in 1.8x. 
#352 is open for the full screen alert banner.
