### ISSUE TITLE
Allow banner types to be fieldable

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#29]
The alert banners will just use the default fields at present.
Councils may want to add their own fields, so we should allow access to the manage fields and manage display ui like eck.

**Comment by andybroomfield** [comment]
If we are going to restore using the view in #28 we need to make it field able as it relies on certain fields being available in a certain structure.

**Comment by andybroomfield** [comment]
I belive the entity needs to regenerated so it has most of the fields are managed through manage display.

Fields on the entity
- Title
- Hide title
- Hide hide link
- Status (put live)
- Uid
- Created
- Changed

Derfault bundle (localgov_alert_banner) should have the following fields
- localgov_type_of_alert (annoucement, minor, major, death of notable person, list field key pair values)
  - 0-announcement|Annoucement
  - 1-minor|Minor alert
  - 2-major|Emergency
  - 3-notable-person|Death of a notable person
- localgov_short_description (change to wysiwyg)
- localgov_link (default the title to More information).

**Comment by danchamp** [comment]
I agree @andybroomfield, I didn't appreciate the consequences of the decisions made when generating the entity scaffolding first time around.
