### ISSUE TITLE
Group as dev dependency

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/localgov_alert_banner#290]
I think `drupal/group` now needs adding as a dev dependency so tests can run see failures here https://github.com/localgovdrupal/localgov_project/actions/runs/6316343354/job/17318874731

I believe that is how `drupal/scheduled_transitions` is handled in https://github.com/localgovdrupal/localgov_alert_banner/blob/1.x/composer.json for the same reasons

@finnlewis, @Adnan-cds, @andybroomfield on thoughts on this?

**Comment by andybroomfield** [comment]
Sounds like a good idea.
Same for localgovdrupal/localgov_core for the full screen alert banner (although that one does not have tests yet!)

**Comment by andybroomfield** [comment]
Question is, which version of Group?

<img width="730" alt="Screenshot 2023-10-02 at 4 09 21 pm" src="https://github.com/localgovdrupal/localgov_alert_banner/assets/1467480/3a719f0a-a469-4f8e-8cab-b6cab9eb8a59">

**Comment by millnut** [comment]
@andybroomfield this is where it will get complex as microsites uses `3`, @Adnan-cds what version of Group is the submodule compatible with?

If it's not targeting a specific version we can probably do;

```json
"drupal/group": "^2 || ^3",
```

**Comment by millnut** [comment]
Hmm it also requires `localgov_microsites_group` which could get complex quickly. Adding @stephen-cox here for his thoughts?

It is starting to feel that this submodule should exist as its own module or a submodule within `localgov_microsites_group` that is dependent on `localgov_microsites_group` and `localgov_alert_banner` not as a submodule within `localgov_alert_banner `

**Comment by andybroomfield** [comment]
@millnut I don't see localgov_microsites_group as [a test dependency here ](https://github.com/localgovdrupal/localgov_alert_banner/blob/93f9a151811f3d7d68b69f780b8e5e30b5adddc5/modules/group_alert_banner/tests/src/Kernel/GroupAlertBannerTest.php#L80C1-L89C5), and thats the only test.

I think the sub module can be used as a generic group plugin, there are just some extra (optional?) config that gets installed on microsites. If group 3 is the what microsites uses it makes sense thats what we target.

**Comment by millnut** [comment]
@andybroomfield sorry that was my bad, it was flagging as it couldn't work out the class due to microsites_group missing when the `localgov_alert_banner` is checked in PHPStan as part of the main project; I'll add some ignores around that

**Comment by Adnan-cds** [comment]
[This snippet](https://github.com/localgovdrupal/localgov_alert_banner/blob/e194de066c3bad4396515c536f327fc3e7d75240/.github/workflows/test.yml#L105) from the Github test runner should have taken care of this issue.  Not sure why it didn't.  Anyway, having drupal/groups:^3 as a dev dependency is not a bad idea.

I can confirm that there is no dependency on localgov_microsites_group.

**Comment by millnut** [comment]
Hi @Adnan-cds the localgov_microsites_group dependency I’m seeing here for the helper https://github.com/localgovdrupal/localgov_alert_banner/blob/1.x/modules/group_alert_banner/group_alert_banner.module#L55. cc: @andybroomfield

**Comment by Adnan-cds** [comment]
That's right.  The [relevant function](https://github.com/localgovdrupal/localgov_alert_banner/blob/e194de066c3bad4396515c536f327fc3e7d75240/modules/group_alert_banner/group_alert_banner.module#L26C15-L26C55) is a hook implementation.  It is triggered only if the localgov_microsites_group module is available and ignored otherwise.

**Comment by millnut** [comment]
Great thanks for clarifying @Adnan-cds I now have a better understanding of how that works now.

**Comment by Adnan-cds** [comment]
No problem.
