### ISSUE TITLE
Test against PHP 8.2

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#308]
Just noticed that we are testing on PHP 8.1 and 8.2 on localgov_project, but only PHP 8.1 here.

https://github.com/localgovdrupal/localgov_project/blob/3.x/.github/workflows/test.yml#L36

Maybe we should update to be consistent. 

@andybroomfield do you want to keep testing against Drupal 9  or happy to switch to just D10?

**Comment by andybroomfield** [comment]
Good question, we arn't using anything Drupal 10 specific, so this still maintains 9.x support, but if that is an ongoing issue I'd consider dropping that in next minor release.
