### ISSUE TITLE
Restore form alter behaviour to work with custom entity

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#31]
The form alter funciton targets the ECK alert banner, so the modified form that moves flags locations no longer gets updated.
This needs to be retargeted to localgov_alert_banner.
````php
  if ($form_id == 'alert_banner_alert_banner_form' || $form_id == 'alert_banner_alert_banner_edit_form' || $form_id == 'localgov_alert_banner_add_form' || $form_id == 'localgov_alert_banner_edit_form') {
````
Also check the form is targeting the right elements.
The form should look like a node edit form, with authoring info in the right sidebar.

**Comment by danchamp** [comment]
This is fixed, and a field group added for alert details to tidy the form.

The 'hide close link' field should probably be in Publishing options, I'm not sure how to reference that group though.

**Comment by andybroomfield** [comment]
Thanks @danchamp will review.
You may be able to add it to the flag group, as there arn't publishing options yet, thats a new group that will have to be created once we work on removing the flag dependancy.

**Comment by danchamp** [comment]
Thanks @andybroomfield using the flag group worked.
