### ISSUE TITLE
Add a local task tab for "Alert Banners" for group module

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_alert_banner#312]
At the moment, if you want to create an alert banner you need to go to  `yoursite.com/group/{group_id}/alert-banner/create` but there is no way to know that is where you need to go unless you read through the code and find the route definition for this.

Can we add a new tab for 'Alert banners' in `group_alert_banner` module to

1. Create a tab called 'Alert banners'
2. Links to a page that lists all the alert banners for that group (if there is any)
3. Has action links for "Add new alert banner" and "Add existing alert banner" (same as our "Content" tab does for nodes

**Comment by andybroomfield** [comment]
@Adnan-cds as your more familliar with this, would you be able to look?

**Comment by markconroy** [comment]
Hi @Adnan-cds 

Just wondering if you happen to have any time to take a look at this issue?

**Comment by Adnan-cds** [comment]
Sorry, Mark.  I was off for nearly two weeks.  I will try to look into it this week.

**Comment by markconroy** [comment]
Oh super. Thanks very much Adnan. Hope you had a nice time away.

**Comment by Adnan-cds** [comment]
Hi Mark,
Time away was so so :)  I am just looking into this in one of our microsites and it seems to do as you have asked for in points 1-3 above.  Wondering if I have misunderstood :(  Here is what I see:

At /group/N:
![microsites-menu-with-highlighted-alert-banner](https://github.com/localgovdrupal/localgov_alert_banner/assets/50206849/adb999f1-ad88-4f6e-9b7c-0d29a14e90f0)

At /group/N/alert-banners:
![microsites-alert-banner-action](https://github.com/localgovdrupal/localgov_alert_banner/assets/50206849/3f98b96b-46ba-403c-913c-31f0b5a0beef)

Please confirm.

**Comment by markconroy** [comment]
I'm still missing those tabs @Adnan-cds and also I get a 404 at group/1/alert-banners

![Screenshot 2024-04-30 at 10 19 57](https://github.com/localgovdrupal/localgov_alert_banner/assets/2183332/a400de30-e093-4a95-858e-17eeda8a5899)

![Screenshot 2024-04-30 at 10 20 18](https://github.com/localgovdrupal/localgov_alert_banner/assets/2183332/470a399a-fe39-4cf3-86e5-8da36d6289ff)

**Comment by Adnan-cds** [comment]
Could you please check what version of the localgov_alert_banner module this site is on?

**Comment by markconroy** [comment]
It's 1.7.4. 

And it's a fresh install of the module.

**Comment by Adnan-cds** [comment]
Thanks for confirming.  Sorry, I should have asked this before.  Is this site on localgov_microsites:3.x or localgov_microsites:4.x?

**Comment by markconroy** [comment]
I _think_ it's microsites 2. It's still on Drupal 9, so maybe that's the issue.

**Comment by Adnan-cds** [comment]
Okay, do me a favour and try on localgov_microsites:3.x and see if it works.  Finn has discovered an [issue](https://github.com/localgovdrupal/localgov_alert_banner/issues/315) with localgov_microsites:4.x and I have raised a fix which is pending review.  So localgov_microsites:3.x is the safest bet right now.  We can look into a work-around for localgov_microsites:2.x if the site you are working on cannot be upgraded immediately.  But first try on a fresh site which is on localgov_microsites:3.x.

**Comment by willguv** [comment]
Thanks for looking at this @Adnan-cds much appreciated!

**Comment by markconroy** [comment]
Hi @Adnan-cds 

Thanks very much. Sorry it's taken me a bit of time to get back to testing this, I was off all last month. 

Testing this on Microsites V3 is working fine. So once the microsites I was working on that was on V2 is upgraded, it should be fine as well.

![Screenshot 2024-05-22 at 14 01 52](https://github.com/localgovdrupal/localgov_alert_banner/assets/2183332/5c1db67a-2048-4b3a-86fd-df7594b097a7)

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
