### ISSUE TITLE
Rationalise permissions and add tests

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_alert_banner#39]
I think permissions are going to be a seperarte issue. 
This is more an issue of what the scaffold generates, and there might be a need for the more granulated permissions anyway, so I'm not sure its something to worry about for alpha.
In terms of the workflow, at BHCC we allow all comms to write the banner, but only the emergency publisher role to publish. Though whether we should define that as a seperate role or a new permissions is something worth investigating. We also have the permission in #35.

As this blocks a lot of issues, i'd rather move this forward and open seperate issues to trim down what we don't need. We do need to write seperate tests to make sure only the right access is granted to author, edit, delete and publish, but first we need to discuss what thos should be.

_Originally posted by @andybroomfield in https://github.com/localgovdrupal/localgov_alert_banner/pull/37_

**Comment by ekes** [comment]
Spun off from #37 

We should certainly make sure there are tests before merging completely.
#35 covers the view permissions, edit permissions may want to be updated.

**Comment by andybroomfield** [comment]
What I was trying to post as a new issue before Github broke and @ekes beat me to it.

Currently the regenerated custom entity in #37 creates the full set of CRUD permissions for

- add alert banner entities
- administer alert banner entities
- delete alert banner entities
- edit alert banner entities
- view published alert banner entities
- view unpublished alert banner entities
- view all alert banner revisions
- revert all alert banner revisions
- delete all alert banner revisions
There is also a permissions generator for each bundle type, located in `AlertBannerEntityPermissions::generatePermissions`.

We need to restore a listing permission #35 `access alert banner listing page`.
There is also a custom permission to access the entity page (used for preview)
`access alert_banner entity page` which may get eliminated by #22 however we should restore it for now.

The module also installs a role, emergency publisher, which is the BHCC role that has access to the banners, and the flag to put them live (though may not have the correct permissions currently.

We need to rationalise the permissions and make the changes in the entity that check for them, and then write tests (kernal?) to check that only those with the assigned permissions can access the functionlity. 

A lot of permissions get generated, though this is a consequnce of allowing multiple bundles.
The CRUD permissions look fairly standard accross Drupal and may actully fine for alpha, however we will still need tests for them.

**Comment by andybroomfield** [comment]
Create a test for both an anonomus user and a user with emergency publisher role.

anon user
- Should be able to view an alert banner in the block
- But not view an alert banner page
- Not be able to edit alert banner, access edit page, or create or delete

Emergency publisher
- Should be able to view alert banner
- Should be able to view alert banner page
- Should be able to view the overview
- Should be able to do all CRUD.

I think that really there are only going to be two permissions. View and Manage alert banners.
However its worth keeping the full set for now for the tests, and then strip down as needed.

**Comment by andybroomfield** [comment]
> Should be able to view an alert banner in the block
We don't need to test this, as the existing alertbanner block test does this.
