### ISSUE TITLE
Implement javascript tests for the hide banner feature

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#41]
> As a site visitor I want to click the hide link on the alert banner and not see it again as I browser the council website.

We need to write a javascript test that.
- Shows an alert banner on the website
- Clicks the hide link
- Loads another page and verifies the alert banner is no longer present.
> As a communications officer, I want to reshow an alert banner a site visitor previously hide when I update it, so they are alerted to new information.

In this test, we need to do the above, then update the existing banner and 
- demonstrate the banner with the new updated information is present.

**Comment by danchamp** [comment]
These tests have been created, but second test is blocked by #45
