### ISSUE TITLE
Update paths for Add / Edit operations

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_alert_banner#65]
> I notices the path includes .../entity-type/bundle/id (bundle not being necessary and actually being a bit confusing on breadcrumb to path); 
> but more important shouldn't the path of the view list be the same as the one created for the collection-list to override it? Or is there a plan to put it somewhere/change the collection-list path?

**Comment by andybroomfield** [comment]
Should follow the same pattern as nodes and live under the alert banners admin view path.
/admin/content/alert-banners/[bundle]/[id]/[operation]
eg.
/admin/content/alert-banners/add
/admin/content/alert-banners/add/localgov-alert-banner/
/admin/content/alert-banners/localgov-alert-banner/1
/admin/content/alert-banners/localgov-alert-banner/1/edit 
etc...

**Comment by ekes** [comment]
The node pattern is:-

/node/[bundle]/add
but once it exists it's
/node/[id]/[operation]
The admin collection-list being
/admin/content
The non-admin collection is
/node

As this is 'content' and it's not content with a non-admin stand-alone view mode:

admin collection-list:
/admin/content/alert-banners
individual view:
/admin/content/alert-banners/[id]
operations:
/admin/content/alert-banners/[id]/[operation]
add types list:
/admin/content/alert-banners/add
add:
/admin/content/alert-banners/add/[bundle]

This is the same pattern as the stand alone (also admin view) 'paragraphs' does.

It also avoids using the partial path part /admin/content/alert-banners/[bundle] which doesn't actually have anything on it. Unless you plan to have separate lists of content for each bundle.

(and the node-type pattern is collection /admin/structure/types ; /admin/structure/types/add; /admin/structure/types/[bundle]/[operation])

**Comment by andybroomfield** [comment]
@ekes Ok, that makes more sense I guess. I don't think many sites will have different bundles so they could just have a filter in the admin view to sort types (How content dashboards work will be another issue I'll raise on main localgov projects).

I'm happy with the above pattern, basically copy what nodes does but sit under the admin dashboard path.
