### ISSUE TITLE
Support different alert banners in different blocks (either derivers or instance configuration)

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#76]
Possible examples:
- Croydon has the Big Bang Announcement, which is only visible on home page (currently a paragraph type).
- BHCC has the Covid information banner, shown on every page except the home page (as a separate Covid info panel is part of the home page). This has graphic icon links to key pieces of information.

The alert banner is now a fully field-able entity and can plug into the entire Drupal ecosystem.
This allows the creation of different kinds of alert banner to suit a content designers needs.
Currently, the alert banner view / block will allow a single banner, regardless of type, to be put live and published.
However the examples above have different scenarios on when they would be displayed.

~~Assume: For now that its always one of each type live.~~
When creating a new alert banner type (bundle), also create a new block to display banners of that type.
Each alert banner block (assuming replacing the view in #42) should display the current live banner of its type, this would allow site administrators to configure the banner when banners of that type would be displayed.

**Comment by andybroomfield** [comment]
This should be a good first issue, although it has a few complications. The main thing is to get the block deriver that creates a block per bundle.

**Comment by andybroomfield** [comment]
An alternative to using a deriver would be to make the type of banners to display on the block a configuration option. This way it will be possible to have multiple bundles in the same block if that is a requirement.

**Comment by finnlewis** [comment]
@iam-jam fancy it?

**Comment by iam-jam** [comment]
I'll take it! cc @finnlewis @andybroomfield

**Comment by andybroomfield** [comment]
Thanks @iam-jam I'd like to see if doing this as an per instance configuration (eg. Choose which banner types to display) is possible first.

More complex banners should be implementable by site builders using views / entity que.

**Comment by iam-jam** [comment]
Ah ok @andybroomfield do you want to pick this up or should I have a go?

**Comment by andybroomfield** [comment]
If you've got time to look at it that would be super helpful @iam-jam and happy to then review.

**Comment by iam-jam** [comment]
Sure thing. I'll get a PR together now.

**Comment by iam-jam** [comment]
Over to you for review @andybroomfield
