### ISSUE TITLE
Consistent naming of modules 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#81]
Glancing down the list of LocaGov extensions on a fresh install, it looks like a number of modules have the readable name "LocalGov Drupal Blah" rather than "LocalGov Blah".

For consistency I think we should remove the word "Drupal" from module names, as it is redundant.

We should also update the https://github.com/localgovdrupal/localgov/wiki/Naming-conventions page to reflect consistent naming conventions for modules.

In this case, "LocalGov Drupal Alert banner" should be named "LocalGov Alert Banner"

**Comment by andybroomfield** [comment]
Closing as PR #82 merged.
