### ISSUE TITLE
Investigate whether using notification message as replacement

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#83]
Contrib module [Notification message](https://www.drupal.org/project/notification_message) does simmilar to this module. Could be a replacement which this module could style.

Initial quick pass.
Pros
- Moving functionality to contrib
- Plug into wider eco system

Cons
- Have to use their editing UX not localgov specific (would have to build overrides)
- Adds a dependency for simple functionality

**Comment by Adnan-cds** [comment]
Let's close this.

**Comment by andybroomfield** [comment]
I think there's enough difference for the moment to keep this as a separate project.
