### ISSUE TITLE
Check usuage of field group and remove if not required

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#84]
Field group is currently in the composer.json, but not declared as a dependency.
The form in `src/Form/AlertBannerEntityForm.php` does not use field group, but defines its own groups.
We need to decide if we should use field group, and then declare that as a dependancy, remove the custom groups in the form and define them as a form display and install via config.
If not, we should at least build some detection around if field group is installed and the components are in other groups, and not assign them to custom ones if a site builder has changed them.

**Comment by Adnan-cds** [comment]
> The form in src/Form/AlertBannerEntityForm.php does not use field group, but defines its own groups.

In that case we can drop it as far as I understand.

If anyone overrides the Entity display mode and use field_group, their site-specific config file will add field_group a dependency.

**Comment by andybroomfield** [comment]
Lets drop field group from this module.

**Comment by andybroomfield** [comment]
I think we did this!
