### ISSUE TITLE
Decide what to do with release tag mix up.

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#89]
Sort most recent release is currently v1.0.1-alpha1. But the Drupal pattern should be v.1.0.0-alpha2.
We can't release v.1.0.0-alpha2 as that will not upgrade those with 1.0.1.
If we delete this release, others who have updgraded will need to reinstall the package.
This might be ok as not many installs now, but we are also close to a v1.0 release anyway we could get this through beta and to v1.0.1 quickly for it not to matter?

Thoughts.

**Comment by finnlewis** [comment]
@ekes and I were discussing this today, we think it will be fine.

We've removed the 1.0.1-alpha1 tag from Packagist and Github, which should result in no changes as it was the same as 1.0.0-alpha1.

So now we should be good to continue the increments

1.0.0-alpha1
1.0.0-alpha2
1.0.0-alpha3

up to (if needed)

1.0.0-beta1
1.0.0-beta2
...

Then 

1.0.0

**Comment by andybroomfield** [comment]
@finnlewis @ekes Thanks, if your happy with that then please go ahead.
