### ISSUE TITLE
RuntimeException: Controller "Drupal\localgov_alert_banner\Controller\AlertBannerEntityController::getStatusFormTitle()" requires that you provide a value for the "$alert_banner" argument.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#91]
When creating a new alert banner, I am seeing this: 

`RuntimeException: Controller "Drupal\localgov_alert_banner\Controller\AlertBannerEntityController::getStatusFormTitle()" requires that you provide a value for the "$alert_banner" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. in Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments() (line 78 of /app/vendor/symfony/http-kernel/Controller/ArgumentResolver.php). `

**Comment by andybroomfield** [comment]
@finnlewis is this the default included alert banner type or a new custom type?

**Comment by andybroomfield** [comment]
The code causing this issue is:
````php
  /**
   * Publish or Unpublish title for alert banner status change form.
   */
  public function getStatusFormTitle(AlertBannerEntityInterface $alert_banner) {
    return $alert_banner->isPublished() ? $this->t('Remove banner') : $this->t('Put banner live');
  }
````
This is for the confirmation page to put an alert banner live.
@ekes your listed as the author, do you have any idea on what is going on?
(I've not been able to replicate the issue, and tests still pass).

Might also have soemthing to do with the following in AlertBannerEntityHtmlRouteProvider.php
````php
  /**
   * Gets the status-form route.
   *
   * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
   *   The entity type.
   *
   * @return \Symfony\Component\Routing\Route|null
   *   The generated route, if available.
   */
  protected function getStatusFormRoute(EntityTypeInterface $entity_type) {
    if ($entity_type->hasLinkTemplate('status-form')) {
      $entity_type_id = $entity_type->id();
      $route = new Route($entity_type->getLinkTemplate('status-form'));
      $route
        ->addDefaults([
          '_entity_form' => "{$entity_type_id}.status",
          '_title_callback' => '\Drupal\localgov_alert_banner\Controller\AlertBannerEntityController::getStatusFormTitle',
        ])
        ->setRequirement('_entity_access', "{$entity_type_id}.update")
        ->setOption('parameters', [
          $entity_type_id => ['type' => 'entity:' . $entity_type_id],
        ]);

      // Entity types with serial IDs can specify this in their route
      // requirements, improving the matching process.
      if ($this->getEntityTypeIdKeyType($entity_type) === 'integer') {
        $route->setRequirement($entity_type_id, '\d+');
      }
      return $route;
    }
  }
````

**Comment by ekes** [comment]
Follow-up I noticed while checking the code #93 @andybroomfield do you want to double check that one?
