### ISSUE TITLE
Use Views for admin interface to list all alerts

### ISSUE THREAD

**Issue by tanc** [localgovdrupal/localgov_alert_banner#95]
At the moment it is possible to create new types of `localgov_alert_banner` with different fields etc. Once a new alert type is created a new entity can be created for this alert type by using the "Add alert banner" button found on the alert listing admin page at `/admin/content/alert-banner`.

Once created the new alert does not show up in the list at `/admin/content/alert-banner`. This is confusing for the site admins or site builders looking to create new alert types.

I suggest we replace `/admin/content/alert-banner` with a View which lists alerts of any type, much like the content overview in core. The redirect after editing an alert would need to redirect to the View instead of it's current destination.

**Comment by andybroomfield** [comment]
Thanks for reporting @tanc.

The manage alert banners itself is a view, localgov_admin_manage_alert_banners
(on a local install http://localgov.lndo.site:8000/admin/structure/views/view/localgov_admin_manage_alert_banners).

I can see its filtered to only display the main alert banner type, so first step would be to remove that filter.
We need to also show which bundle (type of kind, as the name can be confusing as we also have type of alert) on the view and the filter menu. It will get a bit crowded so maybe remove one of the date fields from the display.

This may need an update hook to bring in the amended view.

**Comment by andybroomfield** [comment]
I'll tag this as good first issue, as everything except the update hook should be implentable by altering the view and exporting the updated config. We just need to figure out a way of importing the config, either in an update hook or a dedicated page (in case someone has made changes to the view).

Thoughts @finnlewis @ekes ?

**Comment by tanc** [comment]
> The manage alert banners itself is a view, localgov_admin_manage_alert_banners

Oh! I don't know how I missed that. Well that makes things neater on Lambeth, I can easily change the View.

> We need to also show which bundle

How about "Banner type"?

**Comment by andybroomfield** [comment]
@tanc My concern is that screen is getting a bit crowded, however try it on Lambeth and see what the feedback is.
If your making the change, would you also be able to export your config, replace the view thats in the module and raise a pull request?
We will fiqure out how to handle the config update later and if we need an update hook.
