### ISSUE TITLE
How should the put live banner system work with multiple banner types

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#98]
Currently, the alert banner assumes only 1 banner can be put live at a time (following original BHCC spec).
This works when there is only one banner type.
However limiting to only 1 type can be limiting in terms of fields to be used and alternative layouts.
It's possible to define alternative banner types (bundles). However they are all displayed in a single block, and there is a globally applied limit of only 1 banner regardless of type being live.

Originally it was envisioned that other banner types may use the alert banner module, but would display in their own blocks 
(see #76). Eg the Covid banner on BHCC which is displayed on every page except the home page (avoid duplicating info on the home page) which can also be displayed when an alert is displayed. Currently this implements as its own module and not the alert banner system.

Lambeth have also defined their own banner type, which sometimes replaces the main alert banner, but sometimes they use the normal alert banner.

This raises an issue that separating the alert banner types into their own blocks and making the limit 1 banner per type live problematic for existing sites (or does it?)

We need to decide and rationalise the intended behaviour before proceeding with #76.
Either we:
1. Keep the current behaviour. This means banner types are just so site builders can have different field types and displays modes for themers. The limitation of one banner live would apply across types so only one alert banner regardless of type would be published at a time.
2. Implement the new behaviour as intended by #76. This would mean that each banner type gets its own block and site builders would be able to set visibility rules for each banner type on a per block basis. The limitation of one banner live would apply on a per type basis, so a multiple alert banners would be displayed if they where of different types.
3. Remove the limitation of 1 banner live at a time. This would then make it so the emergency publisher / content designer would have to remove a banner manually themselves. This behaviour originated at BHCC from a comms request so we would need to check desirability to keep it and if it could be made an option ([like single window mode](https://youtu.be/2GkoAa5718Y?t=380)).

**Comment by andybroomfield** [comment]
Example of two stacked alert banners of different types.
<img width="1187" alt="two banners example" src="https://user-images.githubusercontent.com/1467480/101072519-11818700-3596-11eb-9c0b-033ce5eb284e.png">

**Comment by andybroomfield** [comment]
From the product group meeting

> Andy showed the existing LGD functionality - it’s now possible to run different types of banners, with images, full page etc
> Do we still only want to show one banner at a time?
> Finn showed the full page version - we like
> 
> Next steps 
> Break the restriction. As many banners as you like, it’s down to content designers
> “Publish and remove others” button. Andy to investigate, and to submit to distribution
> LGD theme work to be done to enable full page version

**Comment by andybroomfield** [comment]
Its resolved that we remove the limnitation and have an option to unpublish all.
This will mean altering the current set up and confirmation page.

First step is to do the block per bundle support in #76.
That should also only trigger unpublishing of banners of same type.
The next step is to alter the banner block to support displaying mulitple banners of type.
Then lastly add the unpublish others on the confirmation page as an option (default to unpublish others).

**Comment by Adnan-cds** [comment]
Question Andy,
Currently I can enable multiple banners, but I cannot order them.  They are sorted based on last update time.  Is that going to change at all?

FAO @andybroomfield

**Comment by andybroomfield** [comment]
@Adnan-cds In terms of order, it should be Notable Death -> Major -> Minor -> Announcement and then in date updated order.
If something more complex is required, then that can be built with a custom view and entity que or simmilar modules.

If there is a desire to have manual re-ordering then that is a question for the product group in the first instance. I'm not sure how that would work with the admin interface though given the aim is to have multiple types of alert banners here which might also appear in different blocks. The general idea is it should always be quick to publish in an emergency so I would try to avoid added complexity. Maybe it is as simple as adding the sticky at top of lists checkbox?

**Comment by Adnan-cds** [comment]
> In terms of order, it should be Notable Death -> Major -> Minor -> Announcement and then in date updated order.

Thanks Andy.  I missed that part :(  @andybroomfield

**Comment by willguv** [comment]
The default order feels OK to me @andybroomfield - thanks for the info. Agree we shouldn't be making this any more complicated than it need be

**Comment by Adnan-cds** [comment]
I have just copy-pasted Andy's explanation to the [README](https://github.com/localgovdrupal/localgov_alert_banner/pull/112) :)

**Comment by andybroomfield** [comment]
Closing this as the new banners types per block is now merged and banners per path is a different issue.
